# Webpage source
source = 'https://archive.globalpolicy.org/us-westward-expansion/26024-us-interventions.html'

# Title
US_Info = ''' "US Military and Clandestine Operations in Foreign Countries" - 1798-Present by Global Policy Forum December 2005 '''

# Dictionary database of U.S. Military or CIA Interventions from 1798 - 2004 with some exclusions
US_Interventions = {'1798-1800' : {'France' : 'Undeclared naval war against France, marines land in Puerto Plata.'},
                    '1801-1805' : {'Tripoli' : 'War with Tripoli (Libya), called "First Barbary War".'},
                    '1806' : {'Spanish Mexico' : 'Military force enters Spanish territory in headwaters of the Rio Grande.'},'1806-1810' : 	{'Spanish and French in Caribbean' : 'US naval vessels attack French and Spanish shipping in the Caribbean.'},
                    '1810' : {'Spanish West Florida' : 'Troops invade and seize Western Florida, a Spanish possession.'},
                    '1812' : {'Spanish East Florida' : 'Troops seize Amelia Island and adjacent territories.'},
                    '1812' : {'Britain' : 'War of 1812, includes naval and land operations.'},
                    '1813' : {'Marquesas Island' : 	'Forces seize Nukahiva and establish first US naval base in the Pacific.'},
                    '1814' : {'Spanish (East Florida)' : 'Troops seize Pensacola in Spanish East Florida.'},
                    '1814-1825' : {'French, British and Spanish in Caribbean' : 'US naval squadron engages French, British and Spanish shipping in the Caribbean.'},
                    '1815' : 	{'Algiers and Tripoli' : 'US naval fleet under Captain Stephen Decatur wages "Second Barbary War" in North Africa.'},
                    '1816-1819' : {'Spanish East Florida' : "Troops attack and seize Nicholls' Fort, Amelia Island and other strategic locations. Spain eventually cedes East Florida to the US."},
                    '1822-1825' : {'Spanish Cuba and Puerto Rico' : 'Marines land in numerous cities in the Spanish island of Cuba and also in Spanish Puerto Rico.'},
                    '1827' : {'Greece' : 'Marines invade the Greek islands of Argentiere, Miconi and Andross.'},
                    '1831' : {'Falkland/Malvinas Islands' : 'US naval squadrons aggress the Falkland Islands in the South Atlantic.'},
                    '1832' : {'Sumatra, Dutch East Indies' : 'US naval squadrons attack Qallah Battoo.'},
                    '1833' : {'Argentina' : 'Forces land in Buenos Aires and engage local combatants.'},
                    '1835-1836' : {'Peru' : 'Troops dispatched twice for counter-insurgency operations.'},
                    '1836' : {'Mexico' : 'Troops assist Texas war for independence.'},
                    '1837' : {'Canada' : 'Naval incident on the Canadian border leads to mobilization of a large force to invade Canada. War is narrowly averted.'},
                    '1838' : {'Sumatra, Dutch East Indies' : 'US naval forces sent to Sumatra for punitive expedition.'},
                    '1840-1841' : {'Fiji' : 'Naval forces deployed, marines land.'},
                    '1841' : {'Samoa' : 'Naval forces deployed, marines land.'},
                    '1842' : {'Mexico' : 'Naval forces temporarily seize cities of Monterey and San Diego.'},
                    '1843' : {'China' : 'Marines land in Canton.'},
                    '1843' : {'Ivory Coast' : 'Marines land.'},
                    '1846-1848' : {'Mexico' : 'Full-scale war. Mexico cedes half of its territory to the US by the Treaty of Guadeloupe Hidalgo.'},
                    '1849' : {'Ottoman Empire (Turkey)' : 'Naval force dispatched to Smyrna.'},
                    '1852-1853' : {'Argentina' : 'Marines land in Buenos Aires.'},
                    '1854' : {'Nicaragua' : 'Navy bombards and largely destroys city of San Juan del Norte. Marines land and set fire to the city.'},
                    '1854' : {'Japan' : 'Commodore Perry and his fleet deploy at Yokohama.'},
                    '1855' : {'Uruguay' : 'Marines land in Montevideo.'},
                    '1856' : {'Colombia (Panama Region)' : 'Marines land for counter-insurgency campaign.'},
                    '1856' : {'China' : 'Marines deployed in Canton.'},
                    '1856' : {'Hawaii' : 'Naval forces seize small islands of Jarvis, Baker and Howland in the Hawaiian Islands.'},
                    '1857' : {'Nicaragua' : 'Marines land.'},
                    '1858' : {'Uruguay' : 'Marines land in Montevideo.'},
                    '1858' : {'Fiji' : 'Marines land.'},
                    '1859' : {'Paraguay' : 'Large naval force deployed.'},
                    '1859' : {'China' :'Troops enter Shanghai.'},
                    '1859' : {'Mexico' : 'Military force enters northern area.'},
                    '1860' : {'Portuguese West Africa' : 'Troops land at Kissembo.'},
                    '1860' : {'Colombia (Panama Region)' : 'Troops and naval forces deployed.'},
                    '1863' : {'Japan' : 'Troops land at Shimonoseki.'},
                    '1864' : {'Japan' :'Troops landed in Yedo.'},
                    '1865' : {'Colombia (Panama Region)' : 'Marines landed.'},
                    '1866' : {'Colombia (Panama Region)' : 'Troops invade and seize Matamoros, later withdraw.'},
                    '1866' : {'China' : 'Marines land in Newchwang.'},
                    '1867' : {'Nicaragua' : 'Marines land in Managua and Leon in Nicaragua.'},
                    '1867' : {'Formosa Island (Taiwan)' : 'Marines land.'},
                    '1867' : {'Midway Island' : 'Naval forces seize this island in the Hawaiian Archipelago for a naval base.'},
                    '1868' : {'Japan' : 'Naval forces deployed at Osaka, Hiogo, Nagasaki, Yokohama and Negata.'},
                    '1868' : {'Uruguay' : 'Marines land at Montevideo.'},
                    '1870' : {'Colombia' : 'Marines landed.'},
                    '1871' : {'Korea' : 'Forces landed.'},
                    '1873' : {'Colombia (Panama Region)' : 'Marines landed.'},
                    '1874' : {'Hawaii' : 'Sailors and marines landed.'},
                    '1876' : {'Mexico' : 'Army again occupies Matamoros.'},
                    '1882' : {'British Egypt' : 'Troops land.'},
                    '1885' : {'Colombia (Panama Region)' : 'Troops land in Colon and Panama City.'},
                    '1885' : {'Samoa' : 'Naval force deployed.'},
                    '1887' : {'Hawaii' : 'Navy gains right to build permanent naval base at Pearl Harbor.'},
                    '1888' : {'Haiti' : 'Troops landed.'},
                    '1888' : {'Samoa' : 'Marines landed.'},
                    '1889' : {'Samoa' : 'Clash with German naval forces.'},
                    '1890' : {'Argentina' : 'US sailors land in Buenos Aires.'},
                    '1891' : {'Chile' : 'US sailors land in the major port city of Valparaiso.'},
                    '1891' : {'Haiti' : 'Marines land on US-claimed Navassa Island.'},
                    '1893' : {'Hawaii' : "Marines and other naval forces land and overthrow the monarchy. Read More | President Cleveland's Message"},
                    '1894' : {'Nicaragua' : 'Marines land at Bluefields on the eastern coast.'},
                    '1894-1895' : {'China' : 'Marines are stationed at Tientsin and Beijing. A naval ship takes up position at Newchwang.'},
                    '1894-1896' : {'Korea' : 'Marines land and remain in Seoul.'},
                    '1895' : {'Colombia' : 'Marines are sent to the town Bocas del Toro.'},
                    '1896' : {'Nicaragua' : 'Marines land in the port of Corinto.'},
                    '1898' : {'Nicaragua' : 'Marines land at the port city of San Juan del Sur.'},
                    '1898' : {'Guam' : 'Naval forces seize Guam Island from Spain and the US holds the island permanently.'},
                    '1898' : {'Cuba' : 'Naval and land forces seize Cuba from Spain.'},
                    '1898' : {'Puerto Rico' : 'Naval and land forces seize Puerto Rico from Spain and the US holds the island permanently.'},
                    '1898' : {'Philippines' : 'Naval forces defeat the Spanish fleet and the US takes control of the country.'},
                    '1899' : {'Philippines' : 'Military units are reinforced for extensive counter-insurgency operations.'},
                    '1899' : {'Samoa' : 'Naval forces land'},
                    '1899' : {'Nicaragua' : 'Marines land at the port city of Bluefields.'},
                    '1900' : {'China' : 'US forces intervene in several cities.'},
                    '1901' : {'Colombia/Panama' : 'Marines land.'},
                    '1902' : {'Colombia/Panama' : 'US forces land in Bocas de Toro'},
                    '1903' : {'Colombia/Panama' : 'With US backing, a group in northern Colombia declares independence as the state of Panama'},
                    '1903' : {'Guam' : 'Navy begins development in Apra Harbor of a permanent base installation.'},
                    '1903' : {'Honduras' : 'Marines go ashore at Puerto Cortez.'},
                    '1903' : {'Dominican Republic' : 'Marines land in Santo Domingo.'},
                    '1904-1905' : {'Korea' : 'Marines land and stay in Seoul.'},
                    '1906-1909' : {'Cuba' : 'Marines land. The US builds a major naval base at Guantanamo Bay.'},
                    '1907' : {'Nicaragua' : 'Troops seize major centers.'},
                    '1907' : {'Honduras' : 'Marines land and take up garrison in cities of Trujillo, Ceiba, Puerto Cortez, San Pedro, Laguna and Choloma.'},
                    '1908' : {'Panama' : 'Marines land and carry out operations.'},
                    '1910' : {'Nicaragua' : 'Marines land in Bluefields and Corinto.'},
                    '1911' : {'Honduras' : 'Marines intervene.'},
                    '1911-1941' : {'China' : "The US builds up its military presence in the country to a force of 5000 troops and a fleet of 44 vessels patrolling China's coast and rivers."},
                    '1912' : {'Cuba' : 'US sends army troops into combat in Havana.'},
                    '1912' : {'Panama' : 'Army troops intervene.'},
                    '1912' : {'Honduras' : 'Marines land.'},
                    '1912-1933' : {'Nicaragua' : 'Marines intervene. A 20-year occupation of the country follows.'},
                    '1913' : {'Mexico' : 'Marines land at Ciaris Estero.'},
                    '1914' : {'Dominican Republic' : 'Naval forces engage in battles in the city of Santo Domingo.'},
                    '1914' : {'Mexico' : "US forces seize and occupy Mexico's major port city of Veracrus from April through November."},
                    '1915-1916' : {'Mexico' : "An expeditionary force of the US Army under Gen. John J. Pershing crosses the Texas border and penetrates several hundred miles into Mexican territory. Eventually reinforced to over 11,000 officers and men."},
                    '1914-1934' : {'Haiti' : "Troops land, aerial bombardment leading to a 19-year military occupation."},
                    '1916-1924' : {'Dominican Republic' : "Military intervention leading to 8-year occupation."},
                    '1917-1933' : {'Cuba' : "Landing of naval forces. Beginning of a 15-year occupation."},
                    '1918-1920' : {'Panama' : 'Troops intervene, remain on "police duty" for over 2 years.'},
                    '1918-1922' : {'Russia' : 'Naval forces and army troops fight battles in several areas of the country during a five- year period.'},
                    '1919' : {'Yugoslavia' : 'Marines intervene in Dalmatia.'},
                    '1919' : {'Honduras' : 'Marines land.'},
                    '1920' : {'Guatemala' : 'Troops intervene.'},
                    '1922' : {'Turkey' : 'Marines engaged in operations in Smyrna (Izmir).'},
                    '1922-1927' : {'China' : 'Naval forces and troops deployed during 5-year period.'},
                    '1924-1925' : {'Honduras' : 'Troops land twice in two-year period.'},
                    '1925' : {'Panama' : 'Marines land and engage in operations.'},
                    '1927-1934' : {'China' : 'Marines and naval forces stationed throughout the country.'},
                    '1932' : {'El Salvador' : 'Naval forces intervene.'},
                    '1933' : {'Cuba' : 'Naval forces deployed.'},
                    '1934' : {'China' : 'Marines land in Foochow.'},
                    '1946' : {'Iran' : 'Troops deployed in northern province.'},
                    '1946-1949' : {'China' : 'Major US army presence of about 100,000 troops, fighting, training and advising local combatants.'},
                    '1947-1949' : {'Greece' : 'US forces wage a 3-year counterinsurgency campaign.'},
                    '1948' : {'Italy' : 'Heavy CIA involvement in national elections.'},
                    '1948-1954' : {'Philippines' : 'Commando operations, "secret" CIA war.'},
                    '1950-1953' : {'Korea' : 'Major forces engaged in war in Korean peninsula.'},
                    '1953' : {'Iran' : 'CIA overthrows government of Prime Minister Mohammed Mossadegh. Read More'},
                    '1954' : {'Vietnam' : 'Financial and materiel support for colonial French military operations, leads eventually to direct US military involvement.'},
                    '1954' : {'Guatemala' : 'CIA overthrows the government of President Jacobo Arbenz Guzman.'},
                    '1958' : {'Lebanon' : 'US marines and army units totaling 14,000 land.'},
                    '1958' : {'Panama' : 'Clashes between US forces in Canal Zone and local citizens.'},
                    '1959' : {'Haiti' : 'Marines land.'},
                    '1960' : {'Congo' : 'CIA-backed overthrow and assassination of Prime Minister Patrice Lumumba.'},
                    '1960-1964' : {'Vietnam': 'Gradual introduction of military advisors and special forces.'},
                    '1961' : {'Cuba' : 'CIA-backed Bay of Pigs invasion.'},
                    '1962' : {'Cuba' : 'Nuclear threat and naval blockade.'},
                    '1962' : {'Laos' : 'CIA-backed military coup.'},
                    '1963' : {'Ecuador' : 'CIA backs military overthrow of President Jose Maria Valesco Ibarra.'},
                    '1964' : {'Panama' : 'Clashes between US forces in Canal Zone and local citizens.'},
                    '1964' : {'Brazil' : 'CIA-backed military coup overthrows the government of Joao Goulart and Gen. Castello Branco takes power.'},
                    '1965-1975' : {'Vietnam ' : 'Large commitment of military forces, including air, naval and ground units numbering up to 500,000+ troops. Full-scale war, lasting for ten years.'},
                    '1965' : {'Indonesia' : 'CIA-backed army coup overthrows President Sukarno and brings Gen. Suharto to power.'},
                    '1965' : {'Congo' : 'CIA backed military coup overthrows President Joseph Kasavubu and brings Joseph Mobutu to power.'},
                    '1965' : {'Dominican Republic' : '23,000 troops land.'},
                    '1965-1973' : {'Laos' : 'Bombing campaign begin, lasting eight years.'},
                    '1966' : {'Ghana' : 'CIA-backed military coup ousts President Kwame Nkrumah.'},
                    '1966-1967' : {'Guatemala' : 'Extensive counter-insurgency operation.'},
                    '1969-1975' : {'Cambodia' : 'CIA supports military coup against Prince Sihanouk, bringing Lon Nol to power. Intensive bombing for seven years along border with Vietnam.'},
                    '1970' : {'Oman' : 'Counter-insurgency operation, including coordination with Iranian marine invasion.'},
                    '1971-1973' : {'Laos' : 'Invasion by US and South Vietnames forces.'},
                    '1973' : {'Chile' : 'CIA-backed military coup ousts government of President Salvador Allende. Gen. Augusto Pinochet comes to power.'},
                    '1975' : {'Cambodia' : 'Marines land, engage in combat with government forces.'},
                    '1976-1992' : {'Angola' : 'Military and CIA operations.'},
                    '1980' : {'Iran' : 'Special operations units land in Iranian desert. Helicopter malfunction leads to aborting of planned raid.'},
                    '1981' : {'Libya' : 'Naval jets shoot down two Libyan jets in maneuvers over the Mediterranean.'},
                    '1981-1992' : {'El Salvador' : 'CIA and special forces begin a long counterinsurgency campaign.'},
                    '1981-1990' : {'Nicaragua' : 'CIA directs exile "Contra" operations. US air units drop sea mines in harbors.'},
                    '1982-1984' : {'Lebanon' : 'Marines land and naval forces fire on local combatants.'},
                    '1983' : {'Grenada' : 'Military forces invade Grenada.'},
                    '1983-1989' : {'Honduras' : 'Large program of military assistance aimed at conflict in Nicaragua.'},
                    '1984' : {'Iran' : 'Two Iranian jets shot down over the Persian Gulf.'},
                    '1986' : {'Libya' : 'US aircraft bomb the cities of Tripoli and Benghazi, including direct strikes at the official residence of President Muamar al Qadaffi.'},
                    '1986' : {'Bolivia' : 'Special Forces units engage in counter-insurgency.'},
                    '1987-1988' : {'Iran' : 'Naval forces block Iranian shipping. Civilian airliner shot down by missile cruiser.'},
                    '1989' : {'Libya' : 'Naval aircraft shoot down two Libyan jets over Gulf of Sidra.'},
                    '1989' : {'Philippines' : 'CIA and Special Forces involved in counterinsurgency.'},
                    '1989-1990' : {'Panama' : '27,000 troops as well as naval and air power used to overthrow government of President Noriega.'},
                    '1990' : {'Liberia' : 'Troops deployed.'},
                    '1990-1991' : {'Iraq' : 'Major military operation, including naval blockade, air strikes; large number of troops attack Iraqi forces in occupied Kuwait.'},
                    '1991-2003' : {'Iraq' : 'Control of Iraqi airspace in north and south of the country with periodic attacks on air and ground targets.'},
                    '1991' : {'Haiti' : 'CIA-backed military coup ousts President Jean-Bertrand Aristide.'},
                    '1992-1994' : {'Somalia' : 	'Special operations forces intervene.'},
                    '1992-1994' : {'Yugoslavia' : 'Major role in NATO blockade of Serbia and Montenegro.'},
                    '1993-1995' : {'Bosnia' : 'Active military involvement with air and ground forces.'},
                    '1994-1996' : {'Haiti' : 'Troops depose military rulers and restore President Jean-Bertrand Aristide to office.'},
                    '1995' : {'Croatia' : 'Krajina Serb airfields attacked.'},
                    '1996-1997' : {'Zaire (Congo)' : 'Marines involved in operations in eastern region of the country.'},
                    '1997' : {'Liberia' : 'Troops deployed.'},
                    '1998' : {'Sudan' : "Air strikes destroy country's major pharmaceutical plant."},
                    '1998' : {'Afghanistan' : 'Attack on targets in the country.'},
                    '1998' : {'Iraq' : 'Four days of intensive air and missile strikes.'},
                    '1999' : {'Yugoslavia' : 'Major involvement in NATO air strikes.'},
                    '2001' : {'Macedonia' : 'NATO troops shift and partially disarm Albanian rebels.'},
                    '2001' : {'Afghanistan' : 'Air attacks and ground operations oust Taliban government and install a new regime.'},
                    '2003' : {'Iraq' : 'Invasion with large ground, air and naval forces ousts government of Saddam Hussein and establishes new government.'},
                    '2003-present' : {'Iraq' : 'Occupation force of 150,000 troops in protracted counter-insurgency war'},
                    '2004' : {'Haiti' : 'Marines land. CIA-backed forces overthrow President Jean-Bertrand Aristide.'} 
                    }

# Search the database and save to folder
search_database  = input('Enter year or name of country: ').strip()
if search_database in US_Interventions:
     for year, country in US_Interventions[search_database].items(): 
        result = year, country
        print(result)
        with open('Military_History_Project/record/military_record.csv','a') as f:
            f.write('\n')
            f.write(str(result))
            f.close()
            print('Record saved!')
else:
    for year, country in US_Interventions.items():
        country_event = {country: event for country, event in country.items() if search_database.lower() in country.lower()}
        if country_event:
            for country, event in country.items():
                result = year, country, event
                print(result)
            with open('Military_History_Project/record/military_record.csv','a') as f:
                f.write('\n')
                f.write(str(result))
                f.close()
                print('--Record saved--')
    
